"""
Golden-vector cross-engine tests (OPT-A2 — single source of truth).

shared/golden-vectors.json was generated by the TypeScript engine (the
reference implementation). This suite proves the Python Lambda produces the
SAME numbers for every canonical statutory boundary — killing silent
TS↔Python drift, which for tax math is a wrong-tax compliance defect.

Contract: every numeric field must match to the rupee. Prose is excluded by
design (analysis strings and slab labels are presentation, formatted
differently per language runtime).
"""

import json
import os
import sys

import pytest

sys.path.insert(
    0, os.path.join(os.path.dirname(__file__), "..", "src", "lambdas", "tax_calculation")
)
import calculate  # noqa: E402

_VECTORS_PATH = os.path.join(
    os.path.dirname(__file__), "..", "..", "shared", "golden-vectors.json"
)

with open(_VECTORS_PATH, encoding="utf-8") as fh:
    _GOLDEN = json.load(fh)

VECTORS = _GOLDEN["vectors"]

# Rupee-valued fields — exact to the rupee, no tolerance.
_EXACT_FIELDS = [
    "grossTotalIncome", "totalDeductions", "taxableIncome",
    "taxBeforeSurcharge", "surcharge", "surchargeRate",
    "taxAfterSurcharge", "cess", "cessRate", "rebate87A",
    "totalTaxLiability", "takeHomeIncome",
]

# Ratio fields — double arithmetic may round in different orders.
_APPROX_FIELDS = ["effectiveTaxRate"]


def _assert_regime_equal(actual: dict, expected: dict, regime: str, vid: str):
    for field in _EXACT_FIELDS:
        assert actual[field] == expected[field], (
            f"{vid} [{regime}] {field}: python={actual[field]} ts={expected[field]}"
        )
    for field in _APPROX_FIELDS:
        assert actual[field] == pytest.approx(expected[field], abs=0.01), (
            f"{vid} [{regime}] {field}: python={actual[field]} ts={expected[field]}"
        )

    assert actual["incomeBreakdown"] == expected["incomeBreakdown"], (
        f"{vid} [{regime}] incomeBreakdown diverged"
    )
    assert actual["deductionBreakdown"] == expected["deductionBreakdown"], (
        f"{vid} [{regime}] deductionBreakdown diverged"
    )

    # Slab rows: numeric contract only ('slab' label is presentation text).
    act_slabs = actual["slabWiseTax"]
    exp_slabs = expected["slabWiseTax"]
    assert len(act_slabs) == len(exp_slabs), (
        f"{vid} [{regime}] slab count: python={len(act_slabs)} ts={len(exp_slabs)}"
    )
    for i, (a, e) in enumerate(zip(act_slabs, exp_slabs)):
        for key in ("income", "rate", "tax"):
            assert a[key] == e[key], (
                f"{vid} [{regime}] slab[{i}].{key}: python={a[key]} ts={e[key]}"
            )


@pytest.mark.parametrize("vector", VECTORS, ids=[v["id"] for v in VECTORS])
def test_golden_vector_parity(vector):
    """Python engine must reproduce the TS reference output to the rupee."""
    result = calculate.compare_regimes(
        vector["input"]["income"],
        vector["input"]["deductions"],
        vector["input"]["personalInfo"],
    )
    expected = vector["expected"]

    _assert_regime_equal(result["oldRegime"], expected["oldRegime"], "old", vector["id"])
    _assert_regime_equal(result["newRegime"], expected["newRegime"], "new", vector["id"])

    assert result["recommendedRegime"] == expected["recommendedRegime"], vector["id"]
    assert result["savings"] == expected["savings"], vector["id"]
    assert result["savingsPercentage"] == pytest.approx(
        expected["savingsPercentage"], abs=0.01
    ), vector["id"]
    assert result["deductionsLost"] == expected["deductionsLost"], vector["id"]


def test_vector_file_is_current_generation():
    """Guard against a stale vector file (regenerated on statutory change)."""
    assert _GOLDEN["_meta"]["vectorCount"] == len(VECTORS)
    assert _GOLDEN["_meta"]["financialYear"] == "FY2025-26"
